excel:
  sheets_to_keep:
    - 常规产品
    - S级产品
    - 汇总
  date_format: '%Y%m%d_%H%M%S'

date:
  input_formats:
    - '%Y-%m-%d'
    - '%Y/%m/%d'
    - '%Y.%m.%d'
    - '%Y年%m月%d日'
  output_format: '%Y-%m-%d'

feishu:
  app_id: "cli_a63afccc31bc900b"  # 更新后的App ID
  app_secret: "hJLJHYk64H6nCSz3aq77ThJnJUzkOAC5"  # 更新后的App Secret
  spreadsheet_token: 'MdJWsy8N6hLqq7tCz51cPxySntf'
  sheets:
    - sheet_id: 'RjyBZ8'  # S级产品
      sheet_name: 'S级产品'
    - sheet_id: '64v01a'  # 常规产品
      sheet_name: '常规产品'
    - sheet_id: 'cxW3wO'  # 汇总
      sheet_name: '汇总'

styles:
  header:
    green: '1F6B3B'
    orange: 'F4B183'

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_pattern: 'logs/excel_processor_%Y%m%d.log'

output:
  directory: 'output'
  suffixes:
    preprocess: '_preprocessed'
    transform: '_transformed'
    merge: '_merged'